package io.github.cvhhji.gmsnetguard;
import android.content.*;import android.content.pm.*;import android.os.*;import android.util.*;import java.lang.reflect.*;import java.util.*;import dalvik.system.DexFile;import io.github.libxposed.api.XposedModule;
public final class MainHook extends XposedModule{
 static final String TAG="GmsAntiFraudGuard",ANDROID="android",SYSTEM="system",PM="com.coloros.phonemanager";static final Set<String>GOOGLE=new HashSet<>(Arrays.asList("com.google.android.gms","com.android.vending","com.google.android.gsf"));
 static final String[] COMPONENTS={"com.oplus.phonemanager.aivoicecalldetect.antifraudhome.SecurityHomeActivity","com.oplus.phonemanager.aivoicecalldetect.settings.AiVoiceCallDetectSettingsActivity","com.oplus.phonemanager.aivoicecalldetect.riskdetail.ui.AntiFraudSeqDetailsActivity","com.oplus.phonemanager.aivoicecalldetect.antifraudrecords.view.SecurityEventStatisticsActivity","com.oplus.phonemanager.aivoicecalldetect.dialog.FraudRiskDialogActivity","com.oplus.phonemanager.aivoicecalldetect.receiver.InCallRiskDialogReceiver","com.oplus.phonemanager.aivoicecalldetect.trigger.VoipCallDetectTriggerReceiver","com.oplus.phonemanager.aivoicecalldetect.trigger.SimCallDetectTriggerService","com.oplus.phonemanager.aivoicecalldetect.service.AiVoiceDetectForegroundService","com.oplus.phonemanager.aivoicecalldetect.provider.AiVoiceDetectProvider","com.oplus.phonemanager.aivoicecalldetect.provider.FeedbackFileLogProvider","com.oplus.phonemanager.common.provider.FraudDetectRuleFilePipeProvider"};
 public void onModuleLoaded(ModuleLoadedParam p){info("loaded "+p.getProcessName());}
 public void onPackageReady(PackageReadyParam p){String pkg=p.getPackageName();ClassLoader cl=p.getClassLoader();if(ANDROID.equals(pkg)||SYSTEM.equals(pkg)){hookNetworking(cl);hookSystemServer(cl);Context x=currentContext();if(x!=null)new Handler(Looper.getMainLooper()).postDelayed(()->{repair(x);disableFraud(x);},4000);}if(PM.equals(pkg)||pkg.equals("com.android.phone")||pkg.equals("com.android.server.telecom"))neutralizeFraud(cl,p.getApplicationInfo(),pkg);if(PM.equals(pkg)){Context x=currentContext();if(x!=null)disableFraud(x);}else if(SYSTEM.equals(pkg))disableFraudShell();}
 static Context currentContext(){try{return(Context)Class.forName("android.app.ActivityThread").getMethod("currentApplication").invoke(null);}catch(Throwable ignored){return null;}}
 void hookSystemServer(ClassLoader cl){try{Class<?>c=Class.forName("com.android.server.SystemServer",false,cl);for(Method m:c.getDeclaredMethods())if(m.getName().equals("startOtherServices")){hook(m).setId("gms-repair-start").intercept(ch->{Object r=ch.proceed();Context x=context(ch.getThisObject());if(x!=null)new Handler(Looper.getMainLooper()).postDelayed(()->{repair(x);disableFraud(x);},5000);return r;});break;}}catch(Throwable t){err("systemserver",t);}}
 static Context context(Object o){for(Class<?>c=o.getClass();c!=null;c=c.getSuperclass())try{Field f=c.getDeclaredField("mSystemContext");f.setAccessible(true);return(Context)f.get(o);}catch(Throwable ignored){}return null;}
 void hookNetworking(ClassLoader cl){hookNms(cl);hookPolicy(cl,"android.net.OplusNetworkingControlManager");hookPolicy(cl,"android.net.IOplusNetworkingControlManager$Stub$Proxy");try{Class<?>c=Class.forName("com.android.server.nwpower.OAppNetControlService",false,cl);for(Method m:c.getDeclaredMethods()){String n=m.getName();if((n.equals("setFirewall")||n.equals("legacySetFirewall"))&&m.getParameterCount()==2)hook(m).setId("allow-gms-fw-"+n).intercept(ch->{Object[]a=ch.getArgs().toArray();if(a[0]instanceof Integer&&googleUid((Integer)a[0])){a[1]=false;info("prevent firewall uid="+a[0]);return ch.proceed(a);}return ch.proceed();});else if((n.equals("destroySocket")||n.equals("forceStopNetDisbaleWhitelist"))&&m.getParameterCount()==1)hook(m).setId("keep-gms-socket-"+n).intercept(ch->{Object a=ch.getArg(0);if(a instanceof Integer&&googleUid((Integer)a)){info("prevent socket destroy uid="+a);return null;}return ch.proceed();});else if(n.equals("networkDisableWhiteList"))hook(m).setId("gms-net-whitelist").intercept(ch->{Object[]a=ch.getArgs().toArray();if(a[0]instanceof List){List<Object>l=new ArrayList<>((List<?>)a[0]);l.addAll(GOOGLE);a[0]=l;}return ch.proceed(a);});}info("OAppNetControl hooks ready");}catch(Throwable t){err("OAppNetControl",t);}}
 void hookNms(ClassLoader cl){for(String cn:new String[]{"com.android.server.net.NetworkPolicyManagerService","com.android.server.net.NetworkPolicyManagerService$NetworkPolicyManagerInternalImpl"})try{Class<?>c=Class.forName(cn,false,cl);for(Method m:c.getDeclaredMethods()){String n=m.getName();if((n.equals("setUidPolicy")||n.equals("addUidPolicy")||n.equals("setUidFirewallRule")||n.equals("setUidFirewallRuleUL"))&&m.getParameterCount()>=2)hook(m).setId("allow-google-mobile-"+cn+"-"+n).intercept(ch->{Object[]a=ch.getArgs().toArray();int pos=-1;for(int i=0;i<a.length;i++)if(a[i]instanceof Integer&&googleUid((Integer)a[i])){pos=i;break;}if(pos>=0){if((n.equals("setUidPolicy")||n.equals("addUidPolicy"))&&pos+1<a.length&&a[pos+1]instanceof Integer)a[pos+1]=4;else if(a.length>0&&a[a.length-1]instanceof Integer)a[a.length-1]=1;info("prevent metered deny uid="+a[pos]+" via "+n);return ch.proceed(a);}return ch.proceed();});}info("metered policy hooks ready "+cn);}catch(Throwable ignored){}}
 void hookPolicy(ClassLoader cl,String n){try{Class<?>c=Class.forName(n,false,cl);for(Method m:c.getDeclaredMethods())if(m.getName().equals("setUidPolicy")&&m.getParameterCount()>=2)hook(m).setId("allow-google-policy-"+n).intercept(ch->{Object[]a=ch.getArgs().toArray();if(a[0]instanceof Integer&&googleUid((Integer)a[0]))a[1]=0;return ch.proceed(a);});}catch(Throwable ignored){}}
 void repair(Context x){try{PackageManager pm=x.getPackageManager();for(String p:GOOGLE){int u=pm.getPackageUid(p,0);try{Class<?>c=Class.forName("android.net.OplusNetworkingControlManager");Object m=c.getMethod("getOplusNetworkingControlManager").invoke(null);c.getMethod("setUidPolicy",int.class,int.class).invoke(m,u,0);int policy=(Integer)c.getMethod("getUidPolicy",int.class).invoke(m,u);info("oplus policy "+p+"="+policy);}catch(Throwable t){err("policy "+p,t);}try{Object npm=x.getSystemService("netpolicy");Class<?>nc=Class.forName("android.net.NetworkPolicyManager");nc.getMethod("setUidPolicy",int.class,int.class).invoke(npm,u,4);info("metered policy "+p+"=4");}catch(Throwable t){err("metered "+p,t);}try{android.app.usage.UsageStatsManager us=(android.app.usage.UsageStatsManager)x.getSystemService(Context.USAGE_STATS_SERVICE);us.getClass().getMethod("setAppStandbyBucket",String.class,int.class).invoke(us,p,android.app.usage.UsageStatsManager.STANDBY_BUCKET_ACTIVE);}catch(Throwable ignored){}info("repaired "+p+" uid="+u);}}catch(Throwable t){err("repair",t);}}
 void disableFraudShell(){try{for(String c:COMPONENTS)new ProcessBuilder("/system/bin/cmd","package","disable-user","--user","0",PM+"/"+c).start();info("anti-fraud disable commands issued");}catch(Throwable t){err("disable shell",t);}}
 void disableFraud(Context x){for(String c:COMPONENTS)try{x.getPackageManager().setComponentEnabledSetting(new ComponentName(PM,c),PackageManager.COMPONENT_ENABLED_STATE_DISABLED,PackageManager.DONT_KILL_APP);}catch(Throwable t){err("disable "+c,t);}info("anti-fraud components disabled");}
 void neutralizeFraud(ClassLoader cl,ApplicationInfo ai,String pkg){Set<String>s=new HashSet<>();scan(ai.sourceDir,s);if(ai.splitSourceDirs!=null)for(String p:ai.splitSourceDirs)scan(p,s);int n=0;for(String cn:s)try{Class<?>c=Class.forName(cn,false,cl);for(Method m:c.getDeclaredMethods()){Object v=zero(m.getReturnType());hook(m).setId("fraud-"+Integer.toHexString(m.toGenericString().hashCode())).intercept(ch->v);n++;}}catch(Throwable ignored){}info("fraud hooks "+pkg+"="+n);}
 void scan(String p,Set<String>s){try{DexFile d=new DexFile(p);Enumeration<String>e=d.entries();while(e.hasMoreElements()){String raw=e.nextElement(),n=raw.toLowerCase(Locale.ROOT);if(n.contains("fraud")||n.contains("antifraud")||n.contains("aivoicecalldetect"))s.add(raw);}d.close();}catch(Throwable ignored){}}
 static Object zero(Class<?>t){if(t==boolean.class)return false;if(t==byte.class)return(byte)0;if(t==short.class)return(short)0;if(t==int.class)return 0;if(t==long.class)return 0L;if(t==float.class)return 0f;if(t==double.class)return 0d;if(t==char.class)return'\0';return null;}
 boolean googleUid(int u){try{Object pm=Class.forName("android.app.AppGlobals").getMethod("getPackageManager").invoke(null);String[]ps=(String[])pm.getClass().getMethod("getPackagesForUid",int.class).invoke(pm,u);if(ps!=null)for(String p:ps)if(GOOGLE.contains(p))return true;}catch(Throwable ignored){}return false;}
 void info(String s){log(Log.INFO,TAG,s);}void err(String s,Throwable t){log(Log.ERROR,TAG,s,t);}
}
